In [10]:
import numpy
import os

In [11]:
n = numpy.arange(27)
n

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26])

In [12]:
n.reshape(3,9)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23, 24, 25, 26]])

In [13]:
n.reshape(3,3,3)

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [14]:
m = numpy.asarray([123, 12, 123, 12, 33], [], [])
print(m)

[() () () () ()]


In [15]:
type(m)

numpy.ndarray

In [23]:
import cv2
im_g = cv2.imread("smallgray.png", 0)
print(im_g)

[[187 158 104 121 143]
 [198 125 255 255 147]
 [209 134 255  97 182]]


In [21]:
cv2.imwrite("newsmallgray.png", im_g)

True

In [22]:
os.listdir()

['Numpy1.ipynb', 'newsmallgray.png', '.ipynb_checkpoints', 'smallgray.png']

In [26]:
im_g[0:2, 2:4]

array([[104, 121],
       [255, 255]], dtype=uint8)

In [29]:
im_g.shape

(3, 5)

In [30]:
im_g[0,2]

104

In [33]:
for i in im_g:
    print(i)

[187 158 104 121 143]
[198 125 255 255 147]
[209 134 255  97 182]


In [34]:
for i in im_g.flat:
    print(i)

187
158
104
121
143
198
125
255
255
147
209
134
255
97
182


In [35]:
im_g

array([[187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182]], dtype=uint8)

In [42]:
ims = numpy.hstack((im_g,im_g))
ims

array([[187, 158, 104, 121, 143, 187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147, 198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182, 209, 134, 255,  97, 182]], dtype=uint8)

In [44]:
ims = numpy.vstack((im_g,im_g))
ims

array([[187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182],
       [187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182]], dtype=uint8)

In [ ]:
lst = nu